import LetsWorkTogether from "@/components/LetsWorkTogether";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div
      >
        {/*  */}
        {/*  */}
        {/*  */}
        {/*  */}
        <LetsWorkTogether hasTransperantBackground={true} />
      </div>
    </>
  );
}
