import LetsWorkTogether from "@/components/LetsWorkTogether";
import Head from "next/head";
import styles from "./index.module.scss";
import NavBar from "@/components/NavBar";
import React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        {/* <LetsWorkTogether
          hasTransperantBackground={true}
          imgSrc={'gears.svg'}
          title={"Let's work together"}
          discription={"Ready to take the next step? Contact us today to discuss your needs and explore how our expertise can drive your success."}
          href={"/contact"}
          className={styles.worktogether}
        /> */}
        <div className={styles.headerContainer}>
          <video autoPlay loop muted className={styles.video}>
            <source src="/homepageVideo.mp4" type="video/mp4" />
          </video>
          <NavBar />
          <LetsWorkTogether
            title={'UAVs System Design'}
            description={'MARS Robotics® focuses on the innovative design and development of advanced Unmanned Aerial Systems (UAS), covering a wide range from Group 1 to Group 4 classifications.'}
            className={styles.header}
          />
        </div>
      </div>
    </>
  );
}
