// Packages
import React from "react";
import path from "path";
import fs from "fs";
// Components
import Head from "next/head";
import DesktopNavBar from "@/components/DesktopNavBar";
import MobileNavBar from "@/components/MobileNavBar";
import LetsWorkTogether from "@/components/LetsWorkTogether";
// Styles
import styles from './SubServices.module.scss';

const NewsPage = ({ header, chooseUs }) => {
    return (
        <>
            <Head>
                <title>Media</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div>
                <DesktopNavBar />
                <MobileNavBar />
                <LetsWorkTogether
                    title={header?.title}
                    description={header?.description}
                />
                <LetsWorkTogether
                    className={styles.whyChooseSection}
                    title={chooseUs?.title}
                    imgSrc={chooseUs?.imgSrc}
                    description={chooseUs?.description}
                />
            </div>
        </>
    )
}

export async function getStaticPaths() {
    const dirPath = path.join(process.cwd(), 'src/data/subService');
    const files = fs.readdirSync(dirPath);
    const paths = files.map(file => {
        const id = file.replace('.json', '');
        return {
            params: { id },
        };
    });

    if (paths.length > 0) {
        console.warn('No paths found');
    }

    return {
        paths,
        fallback: false,
    };
}

export async function getStaticProps({ params }) {
    const { id } = params;
    const filePath = path.join(process.cwd(), `src/data/subService/${id}.json`);
    const jsonData = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(jsonData) || {};

    return {
        props: {
            ...data,
        },
    };
}

export default NewsPage
