// Packages
import React from "react";
import path from "path";
import fs from "fs";
// Components
import Head from "next/head";
import DesktopNavBar from "@/components/DesktopNavBar";
import MobileNavBar from "@/components/MobileNavBar";
import LetsWorkTogether from "@/components/LetsWorkTogether";
// Styles
import styles from "./Media.module.scss";
import Pagination from "@/components/Pagination";

const ContactPage = ({ header, news = [] }) => {
    const [currentPage, setCurrentPage] = React.useState(0);
    const newsPerPage = 3;
    const currentNews = news?.slice(currentPage * newsPerPage, (currentPage * newsPerPage) + newsPerPage);
    console.log(currentNews);
    return (
        <>
            <Head>
                <title>Media</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div>
                <DesktopNavBar />
                <MobileNavBar />
                <LetsWorkTogether
                    title={header?.title}
                    description={header?.description}
                />
                {news && <div className={styles.news}>
                    <div className={styles.newsContainer}>
                        {
                            currentNews?.map((newCard, index) => (
                                <a key={index} className={styles.newsItem} href={'/media/' + newCard.id}>
                                    <div className={styles.newCard}>
                                        <img
                                            className={styles.image}
                                            src={'https://fastly.picsum.photos/id/459/600/400.jpg?hmac=n3Krd9fH0v3W0RCYNLw6IcI2A17urizqjxYLlv_Df3c'}
                                        />
                                        <div className={styles.info}>
                                            <h2 className={styles.titleCard}>{newCard.title}</h2>
                                            <p className={styles.descriptionCard}>{newCard.description}</p>
                                        </div>
                                    </div>
                                </a>
                            ))
                        }
                    </div>
                    {news.length > newsPerPage && (
                        <Pagination
                            currentPage={currentPage}
                            pageNumbers={Math.ceil(news?.length / newsPerPage)}
                            setPage={setCurrentPage}
                            numberPerPage={newsPerPage}
                        />
                    )}
                </div>}
            </div>
        </>
    )
}


export async function getStaticProps() {
    const filePath = path.join(process.cwd(), 'src/data/mediaPage.json');
    const jsonData = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(jsonData) || {};

    return {
        props: {
            ...data
        },
    };
}

export default ContactPage;